export const IS_AUTHENTICATED = "isAuthenticated"
export const HOME_PAGE = "Home"
export const QA_PAGE = "Q & A"
export const TRAVEL_PAGE = "Travel"
export const RSVP_PAGE = "RSVP"
export const REGISTRY_PAGE = "Registry"
export const SCHEDULE_PAGE = "Schedule"
